### ISSUE TITLE
Audio periodically drops for a second

### ISSUE THREAD

**Issue by Jaage** [vrubleg/soundkeeper#1]
Hello,

This is an awesome tool, makes listening to different media much nicer since there is no 2s delay every time you play audio from a new source.

I have encountered a new problem from SoundKeeper, which is that every 10m or so, audio drops for 1s. Has anyone reported/experienced this before?

Thank you.

**Comment by vrubleg** [comment]
No. Most probably your hardware requires a bit stronger signal. Makes sense to try different stream types. You can check if it happens on `SineA10F1000` that is audible 1000Hz sine with 10% amplitude. If it helps, try lower values like `SineA10F5` that should be inaudible.

**Comment by Jaage** [comment]
So it only seems to happen when Windows 11 sound is set to Dolby Atmos for home theater. It doesn’t happen in stereo and it was not happening before installing SoundKeeper I think but I will double check.

**Comment by Jaage** [comment]
In case anybody else comes across the issue, it seems to have been a bug with Nvidia drivers causing audio to drop periodically with Dolby Atmos. I just happened to start using Atmos and Soundkeeper at the same time.
