### ISSUE TITLE
SoundKeeperSineF10A5 not inaudible (aka total audible) on SoudBlaster Z

### ISSUE THREAD

**Issue by scyto** [vrubleg/soundkeeper#10]
Just FYI

On SoundBlaster Z using Dolby Digital encoder with Logitech Dolby Digital speakers SineF10A5 is audible as low rumble.  This was not the case on sound blaster X4 (USB device) doing encoding. As such seems specific to one type of SoundBlaster doing DD or DTS encoding. 

SineF10A0 was silent and worked.

Not sure you care, but just an FYI incase anyone else insists it is audible but cant articulate why :-)

**Comment by vrubleg** [comment]
Did you try standard non-sine mode? If `SineF10A0` works, `Zero` and `Fluctuate` also should work and are better.

**Comment by scyto** [comment]
lemme test, i moved to the X4 due to windows 11 issues (or rather SB issues with win11) and SineF10A5 was all that worked after trying many variants like All - can't remember if tried zero and fluctuate - probably the former and not the latter.  BRB.

**Comment by scyto** [comment]
A few things:

Firstly it seems I can't properly test on SB Z anymore as it seems SB has added some sort of SPDIF keepalive in their encoder / software / driver now (this would be a new thing).

Secondly, I switched over to the onboard Realtek SPDIF to do some testing (using whatever win11 beta channel uses as driver) to make sure the change in SB Z behavior wasn't actually a change in the win11 beta behavior with SPDIF.  It isn't.

On the Realtek I observed the following:

- `SoundkeerpSineF10A5` as per docs works and connection is kept alive and produces no audible noise (signal is pro-logic2 digital, unlike the SB card which does encoding)
- Switching to either Zero or Fluctuate causes Soundkeeper to not keep the connection alive 
- Adding All didn't fix for Zero or Fluctuate (e.g `SoundkeeperZeroAll.exe`)
- Adding Digital didn't fix for Zero or Fluctuate (e.g `SoundkeeperFluctuateDigital.exe`) 

Note the behavior above with Zero / All / Digital was what I experienced maybe 6mo ago on the SB X4 that caused me to move to the SineF10A5.

FWIW:
- I haven't tested alternate speakers
- I am running version 1.3.3.0      

I am sure this isn't a widespread issue, would you like me try anything else on this install, or close as i no longer need Soundkeeper on the SB Z, well until they break their code again, lol.  either way happy to do some testing on the Realtek if you want me to. My suspicion is something changed in the windows insider rings a few months ago...

thanks for making Soundkeeper it has been super useful to me for a few years solving an issue that made me go nuts :-)
