### ISSUE TITLE
Stopped working today with asio bridge after win 10 update

### ISSUE THREAD

**Issue by Verity-Freedom** [vrubleg/soundkeeper#13]
I using it with my creative g6 (horrible sound card that I will sell someday, I already bought x7), and it was fine, but today my win 10 was updated and it suddenly stopped working with hi fi cable asio bridge. I use it since it makes horrible g6 clicks a little more bearable (it is the worst sound card in the world basically). It works fine without asio bridge.

**Comment by Verity-Freedom** [comment]
Tried system point restore, but it didn't help. Just doesn't work with asio anymore.

**Comment by vrubleg** [comment]
Try the [debug version](https://veg.by/files/winsoft/soundkeeper_debug.7z) of the Sound Keeper. It shows debug logs that you could share here. Maybe something will be visible from there.

**Comment by Verity-Freedom** [comment]
Fixed it only with renaming exe to SoundKeeperSineF10A5.

**Comment by Verity-Freedom** [comment]
How am I supposed to use debug? Just run it and then copy information from cmd? It's easy.

Brown version and sines are working good, only default, all and zero all versions don't work.

**Comment by Verity-Freedom** [comment]
2024/03/16 02:20:32.347 [16340] Sound Keeper v1.3.3.2 [2024/01/27]
02:20:32.348 [16340] Enter main thread.
02:20:32.349 [16340] Windows Build Number: 19045 (leaky WASAPI).
02:20:32.349 [16340] Exe File Name: SoundKeeper64d.exe.
02:20:32.349 [16340] Remaining time to sleeping: 1800 seconds.
02:20:32.349 [16340] Device Type: Primary.
02:20:32.350 [16340] Stream Type: Fluctuate (Frequency: 50.000Hz).
02:20:32.350 [16340] Periodicity: Disabled.
02:20:32.356 [16340] Enter main loop.
02:20:32.357 [16340] Starting...
02:20:32.357 [16340] Getting primary audio device...
02:20:32.358 [16340] Device ID: '{0.0.0.00000000}.{efcb1d35-b625-447d-8bc6-8d66309daf32}'. Form Factor: 1.
02:20:32.358 [11692] Enter rendering thread. Device ID: '{0.0.0.00000000}.{efcb1d35-b625-447d-8bc6-8d66309daf32}'.
02:20:32.359 [11692] Rendering thread mode: 1. Delay: 0.
02:20:32.359 [11692] Render. Device State: 1.
02:20:32.363 [11692] Getting output format...
02:20:32.363 [11692] Format: PCM 2ch 48000Hz 24-bit integer.
02:20:32.363 [11692] Getting mixing format...
02:20:32.364 [11692] Format: PCM 2ch 48000Hz 32-bit float.
02:20:32.379 [11692] Output buffer: 100ms (4800 frames).
02:20:32.382 [11692] Starting rendering...
02:20:32.383 [11692] Enter rendering loop.

**Comment by Verity-Freedom** [comment]
I am using asio because it's making g6 sound clicks, the worst sound card in the world, a little more bearable. My x7 limited second hand is on the way to me, so I will resell this shame of humanity and Creative engineering.

**Comment by Verity-Freedom** [comment]
Idk will wasapi be as effective as asio bridge (I think not, I remember testing it), but with asio I feel almost like a normal human being.

**Comment by vrubleg** [comment]
You can also try `SineF1A1`, maybe it will be enough.
