### ISSUE TITLE
Allow soundkeeper to start at specified volume

### ISSUE THREAD

**Issue by owopeachy** [vrubleg/soundkeeper#14]
My sound device is AGGRESSIVE in its low volume cutting out, what i have to do is run sound keeper as SoundKeeper64AllSineF1A100, but when i do and it starts there is audible popping and i always have to set the volume down to 5 or something after which the hdmi stays active. Would it be possible to get the program to somehow launch at that low volume so i dont have to do it manually every time?

**Comment by vrubleg** [comment]
If I understood you correctly, just set `A` to `5` instead of `100`.

**Comment by owopeachy** [comment]
You did! Sorry, that was a bit of a dumb question but now its resolved thanks
