### ISSUE TITLE
Download no longer available 

### ISSUE THREAD

**Issue by patrickiseengum** [vrubleg/soundkeeper#5]
The download seems no longer available. Website seems unreachable.

**Comment by vrubleg** [comment]
I just checked, everything works as expected. Maybe it was a temporary issue?

**Comment by patrickiseengum** [comment]
Nope, still doesnt work. Maybe an error on my end then. I have a pretty strict firewall. Anyway I tried compiling it myself, first time, and that seemed to work. Problem fixed on my end.

**Comment by vrubleg** [comment]
Maybe there is an issue with access from some specific locations. What country are you from? Could you try to access the website though a different provider (e.g. via your smartphone instead of home internet).

**Comment by patrickiseengum** [comment]
Sorry, completely forgot to test this. Yes it’s just local. When I use a VPN or cellular then your site is perfectly reachable. Thanks for the tip.

Met vriendelijke groet,

Patrick
